version: '3.2'
services:
  app:
    image: ${ECR_REGISTRY}/meeemories:${CIRCLE_SHA1}
    environment:
      - LANG=C.UTF-8
      - RAILS_ENV=test
      - CLOUDINARY_CLOUD_NAME=xxxxx
      - CLOUDINARY_FOLDER_PREFIX=xxxxx
  db:
    image: postgres:10.4
