version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.22.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: login
          command: |
            $(docker run --rm \
                -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
                -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
                kirikiriyamama/awscli --region=ap-northeast-1 ecr get-login --no-include-email)
      - run:
          name: build
          command: |
            docker pull ${ECR_REGISTRY}/meeemories:latest
            docker image build -t ${ECR_REGISTRY}/meeemories:${CIRCLE_SHA1} --cache-from ${ECR_REGISTRY}/meeemories:latest .
      - run:
          name: test
          command: |
            docker-compose -f docker-compose.test.yml up -d db
            docker-compose -f docker-compose.test.yml run --rm app bundle exec rails db:create db:schema:load
            docker-compose -f docker-compose.test.yml run --rm app bundle exec rspec
      - run:
          name: push
          command: |
            docker image push ${ECR_REGISTRY}/meeemories:${CIRCLE_SHA1}
            if [[ ${CIRCLE_BRANCH} = 'master' ]]; then
              docker image tag ${ECR_REGISTRY}/meeemories:${CIRCLE_SHA1} ${ECR_REGISTRY}/meeemories:latest
              docker image push ${ECR_REGISTRY}/meeemories:latest
            fi
      - run:
          name: deploy
          command: |
            if [[ ${CIRCLE_BRANCH} = 'master' ]]; then
              docker run --rm \
                -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
                -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
                ${ECR_REGISTRY}/meeemories-hako oneshot --tag=${CIRCLE_SHA1} definition/meeemories-production.jsonnet bundle exec rails db:migrate
              docker run --rm \
                -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
                -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
                ${ECR_REGISTRY}/meeemories-hako deploy --tag=${CIRCLE_SHA1} definition/meeemories-production.jsonnet
            fi
      - run:
          name: teardown
          command: docker-compose -f docker-compose.test.yml down
          when: always
