version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.22.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run:
          name: login
          command: $(docker run --rm -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} kirikiriyamama/awscli --region=ap-northeast-1 ecr get-login --no-include-email)
      - run:
          name: build
          command: |
            docker pull ${ECR_REPOSITORY}:latest
            docker image build -t ${ECR_REPOSITORY}:${CIRCLE_SHA1} --cache-from ${ECR_REPOSITORY}:latest .
      - run:
          name: test
          command: |
            docker-compose -f docker-compose.test.yml up -d db
            docker-compose -f docker-compose.test.yml run --rm app bundle exec rails db:create db:schema:load
            docker-compose -f docker-compose.test.yml run --rm app bundle exec rspec
      - run:
          name: push
          command: |
            docker image push ${ECR_REPOSITORY}:${CIRCLE_SHA1}
            if [[ ${CIRCLE_BRANCH} = 'master' ]]; then
              docker image tag ${ECR_REPOSITORY}:${CIRCLE_SHA1} ${ECR_REPOSITORY}:latest
              docker image push ${ECR_REPOSITORY}:latest
            fi
      - run:
          name: teardown
          command: docker-compose -f docker-compose.test.yml down
          when: always
