default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: meeemories_development
  username: postgres

test:
  <<: *default
  host: db
  database: meeemories_test
  username: postgres

production:
  <<: *default
  database: meeemories_production
  username: meeemories
  password: <%= ENV['MEEEMORIES_DATABASE_PASSWORD'] %>
